//office: https://thoughtcatalog.com/samantha-newman/2020/04/the-office-trivia-questions-answers/
let office-q: [String] = [
    "The casting team originally wanted who to audition for the role of Dwight?",
    "John Krasinski, Mindy Kaling, and who else were all, at one point, interns at Late Night With Conan O’Brien?",
    "Who almost didn’t work in The Office because he was committed to another NBC show called Come to Papa?",
    "During his embarrassing Dundie award presentation, who is Michael Scott presenting a Dundie award when he sings along to “You Sexy Thing” by ’70s British funk band Hot Chocolate?",
    "Which character became Jim’s love interest after moving to the Stamford branch in season three and joining the Scranton office during the merger?",
    "What county in Pennsylvania is the Dunder Mifflin Scranton branch located in?",
    "What is the exclusive club that Pam, Oscar, and Toby Flenderson establish in the episode “Branch Wars”?",
    "What substance does Jim put office supplies owned by Dwight into?",
    "What is the name of the employee who started as “the temp” in the Dunder Mifflin office?",
    "Rainn Wilson did not originally audition for the iconic beet farming Dwight Schrute; instead, he auditioned for which part?",
    "Dwight owns and runs a farm in his spare time. What does this farm primarily produce?",
    "In the “Diversity Day” episode, what famous comedian’s stand up routine does Michael imitate?",
    "“The Client,” the employees read Michael’s movie script. Which employee read the part of Goldenface?",
    "What does Michael burn his foot on?",
    "Who are the three main members of the party planning committee?",
    "What does Michael pretend to fire Pam over in season one?",
    "What kind of sandwich does Michael have a dream about when he’s the head of Michael Scott Paper Company?",
    "What’s the name of Dwight’s porcupine, who he used to make it look like Jim was pranking him?",
    "What’s in the thermos that Michael offers Pam during morning deliveries for the Michael Scott Paper Company?",
    "What brand is Michael Scott wearing on the day he accidentally wearing a woman’s suit?",
    "Who does Michael wear on his head during the activity on diversity day?",
    "During the episode, “Prince Family Paper,” what’s the secret signal that Dwight and Michael agree on using?",
    "Who calls Jim by the nicknames “Tuna” or “Big Tuna”?",
    "At Jim and Pam’s wedding in the “Niagara” episode, what was Kevin wearing on his feet?",
    "What does Jim use to make Dwight salivate in “Phyllis’ Wedding”?",
    "What does Michael eat instead of ice cream because they don’t have any?",
    "In the episode “The Coup,” the Stamford branch members play what video game with each other?",
    "What of the following colors does Angela think is “whore-ish”?",
    "Jim Halpert knows the flavor of yogurt that Pam likes best; what is it?",
    "Who took over Pam as the receptionist after she went to art school in season 5?",
    "Who runs the warehouse below the Dunder Mifflin offices?",
    "What does Dwight keep a pair of in his car for special occasions?",
    "What is Toby’s daughter’s name?",
    "What is the name of the actor who plays Toby Flenderson?",
    "In 2019, Jenna Fischer and who else started an Office re-watch podcast entitled “The Office Ladies”?",
    "In the episode “Fun Run,” who are the three employees that go out to eat in the middle of the run?",
    "Who served on the jury for the Scranton strangler case?",
    "Who punches a hole in the wall between Michael’s office and the conference room?",
    "NBC passed a pilot for a spin-off called “The Farm.” Who was it about?",
    "After the show was first picked up, what did NBC plan to retitle the series to differentiate it from the original British",
    "What actor starred in the British version of The Office?",
    "Who is the proud owner of a Cornell hockey bobblehead?",
    "Throughout the show, it was revealed that one of the office members graduated High School with Michael. Who was it?",
    "In the Season 4 pilot episode “Fun Run,” what cause does Michael organize a fun run for?",
    "What is the number one rated Country and Western station in Scranton, Pennsylvania? (hint: it’s a bumper sticker on Dwight’s desk)",
    "What color does Dwight paint Michael’s office when he thinks he’s taking over Michael’s job?",
    "In what episode does Jim propose to Pam?",
    "Which network produced “The Office”?",
    "What vegetable does Michael force-feed Kevin?",
    "Whose mother does Michael date?",
    "What is Scranton’s nickname?",
    "In the season 2 episode “Christmas Party,” what Secret Santa gift does Jim get Pam?",
    "Who convinces Dwight that the CIA is recruiting him?",
    "What is the name of Kevin’s cover band?",
    "Where does Jim propose to Pam?",
    "Angela, played by Angela Kinsey, mentions that her favorite song is what?",
    "In the episode “Basketball,” who does Michael say is on the team, ‘of course’?",
    "Where did Michael get his “World’s Best Boss” mug?",
    "In the “St. Patrick’s Day” episode, who gets sick on their first date with Andy?",
    "What did Phyllis ask Michael to do at her wedding?",
    "Who wins the Fun Run in season 4?",
    "What song does Michael dance down the aisle to during Pam and Jim’s wedding?",
    "How does Jan break Michael’s TV in the“Dinner Party” episode?",
    "What actor on The Office shot the opening credit footage?",
    "What actor from The Office and John Krasinski went to the same high school?",
    "What item of clothing does Michael insist on having dry cleaned?",
    "Who is the Regional Manager at Dunder Mifflin?",
    "Who wins the bronze medal in the episode, “Office Olympics”?",
    "In the episode “Diwali,” who attempts to kiss Pam?",
    "How does Michael describe the wine in the episode “Dinner Party”?",
    "Who was a phone operator for 1-800-Dentist when she auditioned for The Office?",
    "Which one of Michael’s girlfriends in The Office was played by Steve Carell’s real-life wife?",
    "Who was responsible for casting The Office characters?",
    "In the episode “Basketball,” after the game between the office workers and warehouse workers, one of the office workers is shown continuously making shots. Which employee is it?",
    "What can Dwight Shrute supposedly raise and lower at his will?",
    "Which warehouse employee was engaged to Pam?",
    "What movie does Michael say that Dwight cried during?",
    "When is Michael’s birthday?",
    "In almost every meeting, Stanley is seen doing what?",
    "Jenna Fischer kept what after the series wrapped up?",
    "Who is the Assistant to the Regional Manager?",
    "Who was sent to anger management?",
    "Which character speaks the first line of the series, and which character delivers the final line?",
    "Who plays Todd Packer, a former employee, and Michael’s friend?",
    "What is Phyllis’s husband’s name, who also happens to work in the same office complex?",
    "Who is the Human Resources representative at Dunder Mifflin?",
    "In the episode “Andy’s Play,” Andy Bernard performed in a local theatre production of what?",
    "In the episode “Take Your Daughter to Work Day,” one employee’s daughter is flirting with Ryan Howard. Whose daughter was it?",
    "What is the name of the annual employee awards night on the show?",
    "In the episode “Goodbye Michael,” what does Pam say Michael seems full of at the end of the episode?",
    "In the episode “Chair Model,” Pam would receive Michael’s chair when he got a new one. Who would get Pam’s chair?",
    "After the Fun Run to beat Rabies, who is the oversized check made out?",
    "Based on where he eats most often, what is Michael Scott’s favorite restaurant?",
    "What art school did Pam go to?",
    ]
    [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ]
    ]
]

