import Foundation
import Swift
import Glibc
mutating func shuffle()
let zelda: [String:String] = [
  "Link":"The main character of the Legend of Zelda series is",
  "Ganondorf":"The main villian of the Legend of Zelda series is",
  "Power":"Ganondorf wields the Triforce of _____",
  "Courage":"Link wields the Triforce of _____",
  "Wisdom":"Zelda wields the Triforce of _____",
  "King of Red Lions":"Link's boat in Wind Waker is named",
  "Master Sword":"Link's sword is called the",
  "Navi":"Links fairy in Ocarina of Time is named",
  "Fi":"The spirit of the Master Sword's name is",
  "Koholint Island":"The location in Link's Awakening is called",
  "Hyrule":"The main location of the Legend of Zelda is",
  "Hylia":"The Main godess in The Legend of Zelda is",
  "Minish":"The real name of the Picori are",
  "Zora":"The race of fish people are called the",
  "Rito":"The race of bird people are called the",
  "Gorons":"The race of rock people are called the",
  "Hylians":"The race of human people are called the",
  "Gerudo":"The race of desert people are called the",
  "Termina":"Where does Majora's Mask take place?",
  "Demise":"The first villan chronologically is",
  "Epona":"Link's Horse is called",
  "Rupees":"Hylian currency is called",
  "King Rhoam":"The last king of Hyrule in Breath of the Wild",
  "Valoo":"Name of the dragon on Dragon Roost in Wind Waker",
  "Din":"_____'s Power",
  "Farore":"_____'s Courage",
  "Nayru":"_____'s Wisdom",
  "Girahim":"The 'Demon Lord'",
  "Tretra":"The pirate who's secretly a princess",
  "Sheik":"Zelda's alterante form",
  "7":"There are ______ sages",
  "Sheikah Slate":"Link's new tool in Breath of the Wild",
  "Picto Box":"Used to take pirctures",
  "Midna":"The Twilight Princess",
  "Revali":"The Rito Champion in Breath of the Wild",
  "Mipha":"The Zora Champion in Breath of the Wild",
  "Urbosa":"The Gerudo Champion in Breath of the Wild",
  "Daruk":"The Goron Champion in Breath of the Wild",
  "Kakariko":"Starting village in Ocarina of Time",
  "Left Hand":"Link uses which hand",
  "Wolf":"In Twilight Princess Link transforms into a",
  "Agahnim":"Ganondorf's alter ego in Link to the Past",
  "Flute":"Link's instrument in the orinal game",
  "Wind Waker":"Wand that Link uses in Wind Waker",
  "Ganon":"Second for of Ganondorf in the boss fight of Ocarina of Time",
